# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Use custom name for the config file.
sphinx:
  configuration: manual/conf.py

# Install required Python packages.
python:
  install:
    - requirements: manual/requirements.txt
